---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  chart:
    spec:
      version: 6.7.1
  values:
    replicaCount: 3
    service:
      type: LoadBalancer
    ui:
      color: "#4f00a3"
