---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 8.7.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 10m
  timeout: 5m
