---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  interval: 10m
  values:
    # configInline:
    #   address-pools:
    #   - name: default
    #     protocol: layer2
    #     addresses:
    #     - 192.168.28.10-192.168.28.40
