---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 60m
  url: https://releases.rancher.com/server-charts/stable
  timeout: 3m
