---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: apps
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    ui:
      color: "#4f00a3"
