---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: demo
  interval: 10m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
    ui:
      color: "#4f00a3"
