---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 60m
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  ref:
    tag: latest
