---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      backupTarget: nfs://192.168.30.11/backup
    longhornUI:
      replicas: 1
    service:
      ui:
        type: LoadBalancer
