---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 60s
  dependsOn:
    - name: core
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/demo
  prune: true
  wait: true
